# Generated by Django 4.0.2 on 2022-02-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержимое СМС')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки для обработки')),
            ],
            options={
                'verbose_name': 'СМС',
                'verbose_name_plural': 'СМС',
                'ordering': ['time_created'],
            },
        ),
    ]
