# Generated by Django 4.0.2 on 2022-02-13 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_sms', '0002_alter_sms_data_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SMS_data',
            new_name='SMSData',
        ),
        migrations.CreateModel(
            name='ParsedMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_generation_time', models.DateTimeField(verbose_name='Время формирования СМС')),
                ('vbat_hi', models.IntegerField(verbose_name='Напряжение батарейки под нагрузкой')),
                ('modem_work_time', models.IntegerField(verbose_name='Время работы модема')),
                ('range_counter', models.IntegerField(verbose_name='Счётчик включений дальномера')),
                ('sms_attempt_counter', models.IntegerField(verbose_name='Счётчик попыток отправки СМС')),
                ('sms_confirmed_counter', models.IntegerField(verbose_name='Счётчик подтвержденных СМС')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('vbat_low', models.IntegerField(verbose_name='Напряжение батарейки без нагрузки')),
                ('sms', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parser_sms.smsdata', verbose_name='Связанное СМС')),
            ],
            options={
                'verbose_name': 'Мета данные из СМС',
                'verbose_name_plural': 'Мета данные из СМС',
                'ordering': ['id'],
            },
        ),
    ]
