# Generated by Django 4.0.2 on 2022-02-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_sms', '0003_rename_sms_data_smsdata_parsedmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedmetadata',
            name='from_accel',
            field=models.BooleanField(default=False, verbose_name='СМС от акселерометра'),
        ),
        migrations.AddField(
            model_name='parsedmetadata',
            name='work_from_LSI',
            field=models.BooleanField(default=False, verbose_name='Работа от LSI'),
        ),
    ]
