# Generated by Django 4.0.2 on 2022-02-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_sms', '0004_parsedmetadata_from_accel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsdata',
            options={'ordering': ['-time_created'], 'verbose_name': 'СМС', 'verbose_name_plural': 'СМС'},
        ),
    ]
