# Generated by Django 4.0.2 on 2022-02-22 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_sms', '0005_alter_smsdata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedMeasureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_time', models.DateTimeField(verbose_name='Время измерения')),
                ('temperature', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Температура')),
                ('range', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Дальномер')),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_sms.smsdata', verbose_name='Связанное СМС')),
            ],
            options={
                'verbose_name': 'Измерение из СМС',
                'verbose_name_plural': 'Измерения из СМС',
                'ordering': ['id'],
            },
        ),
    ]
