# Generated by Django 4.0.2 on 2022-02-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_sms', '0007_alter_parsedmeasuredata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parsedmeasuredata',
            options={'ordering': ['-sms_id'], 'verbose_name': 'Измерение из СМС', 'verbose_name_plural': 'Измерения из СМС'},
        ),
    ]
